server:
  port: 8080
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajasekharbh/SpringCloudConfigServer
          #username: 
          #password: 
          search-paths:
          - DEV/*,QA/*,Perf/*
          force-pull: true
          
            
       